AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Portfolio Serverless API (Contact + Health)

Globals:
  Function:
    Runtime: python3.12
    Timeout: 10
    MemorySize: 256
    Tracing: Active

Resources:
  MessagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PortfolioMessages
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  Api:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - "https://jaysoileau.com"
        AllowHeaders:
          - "content-type"
        AllowMethods:
          - GET
          - POST

  ContactFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Environment:
        Variables:
          TABLE_NAME: !Ref MessagesTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref MessagesTable
      Events:
        ContactPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Path: /contact
            Method: POST
        HealthGet:
          Type: HttpApi
          Properties:
            ApiId: !Ref Api
            Path: /health
            Method: GET

Outputs:
  ApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub "https://${Api}.execute-api.${AWS::Region}.amazonaws.com"
